name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci
        working-directory: slide-decks

      - name: Install playwright
        run: pnpm exec playwright install
        working-directory: slide-decks

      - name: Build
        run: nr build --base /${{github.event.repository.name}}/
        working-directory: slide-decks

      - name: Build Project design course
        run: nr build-project_design --base /${{github.event.repository.name}}/project-design/
        working-directory: slide-decks
      - name: Build Java course
        run: nr build-java --base /${{github.event.repository.name}}/java/
        working-directory: slide-decks
      - name: Build Spring Boot course
        run: nr build-spring_boot --base /${{github.event.repository.name}}/spring-boot/
        working-directory: slide-decks
      - name: Build Nestjs course
        run: nr build-nestjs --base /${{github.event.repository.name}}/nestjs/
        working-directory: slide-decks
      - name: Build Docker course
        run: nr build-docker --base /${{github.event.repository.name}}/docker/
        working-directory: slide-decks
      - name: Build Vuejs course
        run: nr build-vuejs --base /${{github.event.repository.name}}/vuejs/
        working-directory: slide-decks
      - name: Build Reactjs course
        run: nr build-reactjs --base /${{github.event.repository.name}}/reactjs/
        working-directory: slide-decks
      - name: Build Monitoring course
        run: nr build-monitoring --base /${{github.event.repository.name}}/monitoring/
        working-directory: slide-decks

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: slide-decks/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
